[package]
name = "avmetadata"
version = "0.1.0"
authors = ["meh. <meh@schizofreni.co>"]
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"] }
ffmpeg = { git = "https://github.com/meh/rust-ffmpeg", features = ["serde"] }
