[package]
name = "avmetadata"
version = "0.1.0"
authors = ["meh. <meh@schizofreni.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
